### ISSUE TITLE
Lab 02 : Missing inplace param for column drop

### ISSUE THREAD

**Issue by maximepeschard** [ADAEPFL/Labs#1]
In the `Intro to Pandas.ipynb` notebook, in section 1.1.4, the lines : 

~~~python
data.drop('month', axis=1)
data
~~~~

will still display the DataFrame with the 'month' column since the drop operation is not done in-place by default. The `inplace` parameter needs to be specified to do so : 

~~~python
data.drop('month', axis=1, inplace=True)
data
~~~

**Comment by e-bug** [comment]
Otherwise, you can give the `data` copy without the 'month' column to another reference:
```python
data_nomonth = data.drop('month', axis=1)
data_nomonth
```

**Comment by pirroh** [comment]
Nice catch @maximepeschard and @e-bug -- bonus for you!
