### ISSUE TITLE
A missing exercise title in Lab02?

### ISSUE THREAD

**Issue by amirsh** [ADAEPFL/Labs#8]
There is a placeholder for an exercise between exercise 4 and 5 in the following file:
https://github.com/ADAEPFL/Labs/blob/master/02%20-%20Intro%20to%20Pandas/Intro%20to%20Pandas.ipynb
Are we supposed to answer this question in our homework as well? Maybe under the title "Exercise 4.5"?

**Comment by pirroh** [comment]
Sorry for the ambiguity, that cell was meant for the interactive lab session.
It won't be counted for the official homework assignment!
